name: Link Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --accept 200,429,999 --include-fragments "**/*.html" "**/*.md"